"""Initial migration with password support

Revision ID: 1d671f60cbfc
Revises: 
Create Date: 2025-11-23 22:03:06.285684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d671f60cbfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_persons_email'), ['email'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=False),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_map_url', sa.String(length=500), nullable=True),
    sa.Column('rsvp_deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('created_by_person_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_uuid'), ['uuid'], unique=True)

    op.create_table('household_memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_primary_contact', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.create_index('idx_active_memberships', ['household_id', 'left_at'], unique=False)
        batch_op.create_index('idx_person_household', ['person_id', 'household_id'], unique=False)

    op.create_table('event_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(person_id IS NOT NULL) OR (household_id IS NOT NULL)', name='check_admin_target'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_admins', schema=None) as batch_op:
        batch_op.create_index('idx_event_admins', ['event_id', 'removed_at'], unique=False)

    op.create_table('event_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=False),
    sa.Column('invitation_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'household_id', name='unique_event_household'),
    sa.UniqueConstraint('invitation_token')
    )
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.create_index('idx_invitation_token', ['invitation_token'], unique=False)

    op.create_table('message_wall_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_organizer_post', sa.Boolean(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_wall_posts', schema=None) as batch_op:
        batch_op.create_index('idx_event_messages', ['event_id', 'posted_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('idx_notification_status', ['event_id', 'status'], unique=False)
        batch_op.create_index('idx_notification_type', ['event_id', 'notification_type'], unique=False)
        batch_op.create_index('idx_person_notifications', ['person_id', 'sent_at'], unique=False)

    op.create_table('potluck_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('dietary_tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('quantity_needed', sa.Integer(), nullable=True),
    sa.Column('created_by_person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'person_id', name='unique_event_person_rsvp')
    )
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.create_index('idx_event_household_rsvp', ['event_id', 'household_id'], unique=False)
        batch_op.create_index('idx_rsvp_status', ['event_id', 'status'], unique=False)

    op.create_table('potluck_claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('potluck_item_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['potluck_item_id'], ['potluck_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('potluck_item_id', 'person_id', name='unique_item_person_claim')
    )
    with op.batch_alter_table('potluck_claims', schema=None) as batch_op:
        batch_op.create_index('idx_potluck_claims', ['potluck_item_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potluck_claims', schema=None) as batch_op:
        batch_op.drop_index('idx_potluck_claims')

    op.drop_table('potluck_claims')
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.drop_index('idx_rsvp_status')
        batch_op.drop_index('idx_event_household_rsvp')

    op.drop_table('rsvps')
    op.drop_table('potluck_items')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_person_notifications')
        batch_op.drop_index('idx_notification_type')
        batch_op.drop_index('idx_notification_status')

    op.drop_table('notifications')
    with op.batch_alter_table('message_wall_posts', schema=None) as batch_op:
        batch_op.drop_index('idx_event_messages')

    op.drop_table('message_wall_posts')
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.drop_index('idx_invitation_token')

    op.drop_table('event_invitations')
    with op.batch_alter_table('event_admins', schema=None) as batch_op:
        batch_op.drop_index('idx_event_admins')

    op.drop_table('event_admins')
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.drop_index('idx_person_household')
        batch_op.drop_index('idx_active_memberships')

    op.drop_table('household_memberships')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_uuid'))

    op.drop_table('events')
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_persons_email'))

    op.drop_table('persons')
    op.drop_table('households')
    # ### end Alembic commands ###
