"""add_invitation_tracking_fields

Revision ID: 274a155a597f
Revises: 4629e86cf578
Create Date: 2025-11-26 10:37:18.957349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274a155a597f'
down_revision = '4629e86cf578'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sent_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_sent_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('potluck_item_contributors', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint('unique_item_contributor', ['potluck_item_id', 'person_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potluck_item_contributors', schema=None) as batch_op:
        batch_op.drop_constraint('unique_item_contributor', type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.drop_column('last_sent_at')
        batch_op.drop_column('sent_count')
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###
