"""Add SMS support fields to Person and EventInvitation

Revision ID: 2ccd9d340ca5
Revises: 274a155a597f
Create Date: 2025-11-30 10:41:12.704712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccd9d340ca5'
down_revision = '274a155a597f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Some columns may already exist from a partial migration.
    # Using batch_alter_table with recreate='never' to handle this gracefully.

    # Check which columns already exist and only add missing ones
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # Get existing columns for event_invitations
    ei_columns = {col['name'] for col in inspector.get_columns('event_invitations')}

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        if 'short_token' not in ei_columns:
            batch_op.add_column(sa.Column('short_token', sa.String(length=16), nullable=True))
        if 'sms_sent_at' not in ei_columns:
            batch_op.add_column(sa.Column('sms_sent_at', sa.DateTime(), nullable=True))
        if 'sms_sent_count' not in ei_columns:
            batch_op.add_column(sa.Column('sms_sent_count', sa.Integer(), nullable=False, server_default='0'))
        if 'sms_last_sent_at' not in ei_columns:
            batch_op.add_column(sa.Column('sms_last_sent_at', sa.DateTime(), nullable=True))

        # Check if index exists
        ei_indexes = {idx['name'] for idx in inspector.get_indexes('event_invitations')}
        if 'ix_event_invitations_short_token' not in ei_indexes:
            batch_op.create_index(batch_op.f('ix_event_invitations_short_token'), ['short_token'], unique=True)

    # Get existing columns for persons
    persons_columns = {col['name'] for col in inspector.get_columns('persons')}

    with op.batch_alter_table('persons', schema=None) as batch_op:
        if 'preferred_contact_method' not in persons_columns:
            batch_op.add_column(sa.Column('preferred_contact_method', sa.String(length=20), nullable=False, server_default='email'))
        if 'sms_opt_in' not in persons_columns:
            batch_op.add_column(sa.Column('sms_opt_in', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('sms_opt_in')
        batch_op.drop_column('preferred_contact_method')

    with op.batch_alter_table('event_invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_invitations_short_token'))
        batch_op.drop_column('sms_last_sent_at')
        batch_op.drop_column('sms_sent_count')
        batch_op.drop_column('sms_sent_at')
        batch_op.drop_column('short_token')

    # ### end Alembic commands ###
