"""Add GuestReferral model and make RSVP household_id nullable

Revision ID: 482bfbe4bda5
Revises: 34abe2b1de29
Create Date: 2025-12-04 18:14:46.295519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482bfbe4bda5'
down_revision = '34abe2b1de29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('referrer_person_id', sa.Integer(), nullable=False),
    sa.Column('referred_person_id', sa.Integer(), nullable=False),
    sa.Column('invitation_token', sa.String(length=500), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('short_token', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['referred_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['referrer_person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'referred_person_id', name='unique_event_referred_person'),
    sa.UniqueConstraint('invitation_token')
    )
    with op.batch_alter_table('guest_referrals', schema=None) as batch_op:
        batch_op.create_index('idx_referral_event', ['event_id'], unique=False)
        batch_op.create_index('idx_referral_referrer', ['referrer_person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_referrals_short_token'), ['short_token'], unique=True)

    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.alter_column('household_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.alter_column('household_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('guest_referrals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_referrals_short_token'))
        batch_op.drop_index('idx_referral_referrer')
        batch_op.drop_index('idx_referral_event')

    op.drop_table('guest_referrals')
    # ### end Alembic commands ###
