"""Add sent tracking fields to guest_referrals

Revision ID: 4cc0db47310c
Revises: 482bfbe4bda5
Create Date: 2025-12-12 18:24:33.856631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cc0db47310c'
down_revision = '482bfbe4bda5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_referrals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sent_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_referrals', schema=None) as batch_op:
        batch_op.drop_column('last_sent_at')
        batch_op.drop_column('sent_count')
        batch_op.drop_column('sent_at')

    # ### end Alembic commands ###
