"""Add suggested potluck items support

Revision ID: 74dec6981ac0
Revises: 56a7e7dc10bb
Create Date: 2025-11-30 11:36:28.224189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74dec6981ac0'
down_revision = '56a7e7dc10bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potluck_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suggested', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('claimed_by_person_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('claimed_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_potluck_items_claimed_by_person', 'persons', ['claimed_by_person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potluck_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_potluck_items_claimed_by_person', type_='foreignkey')
        batch_op.drop_column('claimed_at')
        batch_op.drop_column('claimed_by_person_id')
        batch_op.drop_column('is_suggested')

    # ### end Alembic commands ###
