"""Add PersonInvitationLink for person-specific short links

Revision ID: 88d384309f8d
Revises: bdbe057e1d71
Create Date: 2025-11-30 12:29:37.235967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88d384309f8d'
down_revision = 'bdbe057e1d71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person_invitation_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitation_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('short_token', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['event_invitations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitation_id', 'person_id', name='uq_person_invitation_link')
    )
    with op.batch_alter_table('person_invitation_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_invitation_links_short_token'), ['short_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_invitation_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_invitation_links_short_token'))

    op.drop_table('person_invitation_links')
    # ### end Alembic commands ###
