"""Add RSVP update tracking fields

Revision ID: 8c448bc5d5db
Revises: c6b659f6e3f6
Create Date: 2025-11-24 18:05:03.254221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c448bc5d5db'
down_revision = 'c6b659f6e3f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_by_person_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_by_host', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.create_foreign_key('fk_rsvp_updated_by_person', 'persons', ['updated_by_person_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rsvp_updated_by_person', type_='foreignkey')
        batch_op.drop_column('updated_by_host')
        batch_op.drop_column('updated_by_person_id')

    # ### end Alembic commands ###
