"""Add claimer notes and dietary tags to suggested items

Revision ID: bdbe057e1d71
Revises: 74dec6981ac0
Create Date: 2025-11-30 12:08:33.139683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbe057e1d71'
down_revision = '74dec6981ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potluck_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('claimer_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('claimer_dietary_tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('potluck_items', schema=None) as batch_op:
        batch_op.drop_column('claimer_dietary_tags')
        batch_op.drop_column('claimer_notes')

    # ### end Alembic commands ###
