"""Remove is_primary_contact from household_memberships

Revision ID: c6b659f6e3f6
Revises: 1d671f60cbfc
Create Date: 2025-11-24 17:52:26.664663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b659f6e3f6'
down_revision = '1d671f60cbfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.drop_column('is_primary_contact')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary_contact', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
